trigger: none

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev

  values:
  - dev
  - test
  - stage
  - prod

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'terraform-service-connection'

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: azurerm
    command: init
    backendServiceArm: $(serviceConnection)
    backendAzureRmResourceGroupName: terraform-backend-rg
    backendAzureRmStorageAccountName: tfstatekalyani001
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: '${{ parameters.environment }}.tfstate'

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: azurerm
    command: plan
    commandOptions: >
      -var-file=environments/${{ parameters.environment }}.tfvars
      -out=tfplan
    environmentServiceNameAzureRM: $(serviceConnection)

- task: ManualValidation@0
  displayName: Reviewer approval
  inputs:
    notifyUsers: ''
    instructions: 'Review the Terraform plan output in the pipeline logs. Approve to continue to apply.'
    onTimeout: 'reject'
    timeout: '4320'

- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: azurerm
    command: apply
    commandOptions: >
      -auto-approve
      tfplan
    environmentServiceNameAzureRM: $(serviceConnection)
