trigger: none

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev

  values:
  - dev
  - test
  - stage
  - prod

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'terraform-service-connection'

steps:

- task: AzureCliV2@1
  displayName: Install Terraform
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Install Terraform
      wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
      unzip /tmp/terraform.zip -d /usr/local/bin
      terraform --version

- task: AzureCliV2@1
  displayName: Terraform Init
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init \
        -backend-config="resource_group_name=terraform-backend-rg" \
        -backend-config="storage_account_name=tfstatekalyani001" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=${{ parameters.environment }}.tfstate"

- task: AzureCliV2@1
  displayName: Terraform Plan
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform plan \
        -var-file=environments/${{ parameters.environment }}.tfvars \
        -out=tfplan

- task: AzureCliV2@1
  displayName: Terraform Apply
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform apply \
        -auto-approve \
        tfplan
